# Generated by Django 4.2.30 on 2026-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_transaction_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('top_up', 'Wallet Top-up'), ('payment', 'Payment Received'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('deduction', 'Deduction')], max_length=20),
        ),
    ]
