# Generated by Django 4.2.30 on 2026-07-13 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
        ('admin_portal', '0022_studio_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0011_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(blank=True, help_text='Auto-generated: ORR-REQ-000001', max_length=20, unique=True)),
                ('submission_date', models.DateTimeField(blank=True, help_text='Auto-recorded on submission.', null=True)),
                ('request_title', models.CharField(help_text='Short title for the request.', max_length=300)),
                ('main_request_type', models.CharField(choices=[('advice', 'I need advice'), ('written_review', 'I need a written review or report'), ('operational_problem', 'I need help solving an operational problem'), ('compliance_regulatory', 'I need compliance or regulatory support'), ('it_systems', 'I need IT / systems support'), ('land_agriculture_environment', 'I need land, agriculture, or environmental support'), ('ongoing_support', 'I need ongoing support'), ('not_sure', 'I am not sure')], help_text='What do you need ORR to help with?', max_length=50)),
                ('orr_service_area', models.CharField(blank=True, choices=[('strategy_advisory_compliance', 'Strategy Advisory & Compliance'), ('operational_systems_infrastructure', 'Operational Systems & Infrastructure'), ('living_systems_regeneration', 'Living Systems Regeneration'), ('not_sure', 'Not sure')], help_text="Which ORR service area best fits? If 'Not sure', Admin/PM can classify later.", max_length=50)),
                ('short_description', models.TextField(help_text='Core intake field. Feeds Admin review and AI project summary generation.')),
                ('desired_outcome', models.TextField(help_text='What outcome the client is hoping to achieve.')),
                ('background_context', models.TextField(blank=True, help_text='Background information to help ORR understand the situation.')),
                ('main_question', models.TextField(blank=True, help_text='Useful for advisory and strategy requests.')),
                ('current_challenge', models.TextField(blank=True, help_text='Helps identify urgency, risk, and next action.')),
                ('actions_taken', models.TextField(blank=True, help_text='Prevents duplication and gives PM context.')),
                ('decision_needed', models.TextField(blank=True, help_text='Useful for converting request into project scope.')),
                ('expected_support', models.JSONField(blank=True, default=list, help_text='Multi-select: Initial consultation, Written advice, Document review, etc.')),
                ('expected_deliverable', models.JSONField(blank=True, default=list, help_text='Multi-select: Meeting summary, Advisory note, Written report, etc.')),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('priority', 'Priority'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', help_text='How urgent is this request?', max_length=10)),
                ('target_date', models.DateField(blank=True, help_text='Is there a deadline or target date?', null=True)),
                ('budget_expectation', models.CharField(blank=True, choices=[('not_sure', 'Not sure'), ('small_initial_review', 'Small initial review only'), ('fixed_project_budget', 'Fixed project budget'), ('retainer_support', 'Retainer support'), ('prefer_to_discuss', 'I prefer to discuss')], help_text='Do you already have a budget expectation for this request?', max_length=30)),
                ('sector', models.JSONField(blank=True, default=list, help_text='Multi-select + Other: Agriculture, IT / Software, Regulatory Affairs, etc.')),
                ('jurisdiction', models.TextField(blank=True, help_text='Which country or jurisdiction does this request concern?')),
                ('location', models.TextField(blank=True, help_text='Location of the business, project, land, asset, or operation.')),
                ('has_documents', models.BooleanField(default=False, help_text='Do you have documents that may help ORR assess this request?')),
                ('sensitivity_level', models.CharField(choices=[('standard', 'Standard'), ('confidential', 'Confidential'), ('highly_confidential', 'Highly Confidential'), ('restricted', 'Restricted / commercially sensitive')], default='standard', help_text='How sensitive is this request?', max_length=30)),
                ('confidentiality_agreed', models.BooleanField(default=False, help_text='Sensitive Information Notice acknowledgement.')),
                ('preferred_next_step', models.CharField(blank=True, choices=[('schedule_consultation', 'Schedule a first consultation'), ('receive_feedback', 'Receive initial feedback from ORR'), ('upload_documents', 'Upload documents first'), ('discuss_pricing', 'Discuss pricing'), ('not_sure', 'I am not sure')], help_text='What would you prefer as the next step?', max_length=30)),
                ('preferred_contact_method', models.JSONField(blank=True, default=list, help_text='Multi-select: Portal message, Email, Phone, Video meeting, WhatsApp.')),
                ('preferred_meeting_language', models.JSONField(blank=True, default=list, help_text='Multi-select: English, Maltese, Italian, French, Spanish, Other.')),
                ('confirm_accuracy', models.BooleanField(default=False, help_text='I confirm that the information provided is accurate.')),
                ('confirm_authority', models.BooleanField(default=False, help_text='I confirm that I am authorised to submit this request.')),
                ('confirm_no_emergency', models.BooleanField(default=False, help_text='I understand this does not create an emergency support obligation.')),
                ('ai_processing_notice', models.BooleanField(default=False, help_text='I understand ORR may use secure internal AI-assisted tools.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_orr_review', 'Pending ORR Review'), ('clarification_requested', 'Clarification Requested'), ('approved_for_meeting', 'Approved for Meeting'), ('approved_for_pm_assignment', 'Approved for PM Assignment'), ('converted_to_project', 'Converted to Project'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', help_text='Status drives client visibility and internal workflow.', max_length=30)),
                ('admin_classification', models.TextField(blank=True, help_text='Admin can reclassify service area, urgency, sensitivity, and next step.')),
                ('admin_review_notes', models.TextField(blank=True)),
                ('assigned_pm', models.ForeignKey(blank=True, help_text='If request is approved, Admin can assign client/request to PM.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Linked Client ID. Client should not manually enter this.', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='admin_portal.client')),
                ('converted_project', models.ForeignKey(blank=True, help_text='One request may become one or more projects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='pm.pmproject')),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='Store user ID of last editor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_requests', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='User account ID of the person submitting the request.', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Request',
                'verbose_name_plural': 'Client Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRequestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='client.clientrequest')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ClientRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Upload documents relevant to this request.', upload_to='request_documents/')),
                ('file_name', models.CharField(blank=True, max_length=300)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Briefly describe what each uploaded document is.')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='client.clientrequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vault_document', models.ForeignKey(blank=True, help_text='Link to existing Client Vault document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_links', to='admin_portal.clientdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['client', '-created_at'], name='clientreq_client_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['status'], name='clientreq_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['assigned_pm'], name='clientreq_pm_idx'),
        ),
    ]
