# Generated by Django 4.2.30 on 2026-07-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_clientrequest_clientrequestversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='source',
            field=models.CharField(choices=[('client_portal', 'Client Portal'), ('internally_sourced', 'Internally Sourced')], default='client_portal', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(choices=[('client_portal', 'Client Portal'), ('internally_sourced', 'Internally Sourced')], default='client_portal', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
