# Generated by Django 5.2.8 on 2026-08-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_activity_created_by_activity_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingquestionnaire',
            name='ai_preference',
            field=models.CharField(choices=[('concise', 'Concise'), ('scientific', 'Scientific/Technical'), ('friendly', 'Friendly/Conversational'), ('professional', 'Professional/Formal')], default='concise', max_length=50),
        ),
    ]
