# Generated by Django 5.2.8 on 2026-08-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_onboardingquestionnaire_ai_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='classification',
            field=models.CharField(choices=[('strategy', 'Strategy & Advisory'), ('operations', 'Operational Systems'), ('living_systems', 'Living Systems'), ('mixed', 'Mixed')], default='strategy', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='confidentiality_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('high', 'High'), ('strict', 'Strict')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='internal_review_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_consultants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='roadmap',
            field=models.TextField(blank=True, help_text='Project Roadmap'),
        ),
        migrations.AddField(
            model_name='project',
            name='urgent_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
    ]
