# Generated by Django 5.2.8 on 2026-08-10 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogpost_created_by_blogpost_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticscasestudy',
            name='active_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyticscasestudy',
            name='avg_session_length',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='analyticscasestudy',
            name='current_knowledge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='analyticscasestudy',
            name='knowledge_gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='analyticscasestudy',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyticscasestudy',
            name='starting_knowledge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='industryinsight',
            name='real_time_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='industryinsight',
            name='total_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='industryinsight',
            name='visit_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
