# Generated by Django 4.2.30 on 2026-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0018_clientdocument_access_rule_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document_source',
            field=models.CharField(choices=[('file', 'File'), ('google_doc', 'Google Doc'), ('google_sheet', 'Google Sheet'), ('google_slide', 'Google Slide')], default='file', max_length=20),
        ),
    ]
