# Generated by Django 4.2.30 on 2026-05-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0019_clientdocument_file_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdocument',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client', 'is_visible_to_client'], name='clientdoc_client_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client', 'visibility'], name='clientdoc_client_vis_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client', '-updated_at'], name='clientdoc_client_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['folder'], name='clientdoc_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['-updated_at'], name='clientdoc_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['visibility'], name='clientdoc_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultfolder',
            index=models.Index(fields=['client'], name='vaultfolder_client_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultfolder',
            index=models.Index(fields=['parent'], name='vaultfolder_parent_idx'),
        ),
    ]
