# Generated by Django 4.2.30 on 2026-05-30 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0020_vault_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='can_approve_sensitive_actions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_configure_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_view_audit_logs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_view_security_events',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_enforced', models.BooleanField(default=True)),
                ('ip_bounds_restricted', models.BooleanField(default=False)),
                ('strict_interceptors', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('verbose_logging', models.BooleanField(default=False)),
                ('session_timeout', models.CharField(default='1h', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_category', models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('DUAL_APPROVALS', 'Dual Approvals'), ('DELETIONS', 'Deletions'), ('SYSTEMS', 'Systems'), ('ROLE_CHANGES', 'Role Changes')], max_length=50)),
                ('event_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-event_timestamp'],
                'indexes': [models.Index(fields=['-event_timestamp'], name='secaudit_timestamp_idx'), models.Index(fields=['event_category'], name='secaudit_category_idx'), models.Index(fields=['user_id'], name='secaudit_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalQueue',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('requested_by', models.CharField(max_length=50)),
                ('requested_by_name', models.CharField(blank=True, max_length=150)),
                ('requested_by_role', models.CharField(blank=True, max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('decided_by', models.CharField(blank=True, max_length=50)),
                ('decided_by_name', models.CharField(blank=True, max_length=150)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='approvalqueue_status_idx'), models.Index(fields=['-requested_at'], name='approvalqueue_requested_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
    ]
