# Generated by Django 4.2.30 on 2026-07-01 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0021_adminrole_can_approve_sensitive_actions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Untitled', max_length=500)),
                ('type', models.CharField(choices=[('doc', 'Document'), ('sheet', 'Spreadsheet'), ('slide', 'Presentation')], max_length=10)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('is_trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_documents', to='admin_portal.vaultfolder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='studiodoc_owner_updated_idx'), models.Index(fields=['owner', 'type'], name='studiodoc_owner_type_idx'), models.Index(fields=['folder'], name='studiodoc_folder_idx'), models.Index(fields=['is_trashed'], name='studiodoc_trashed_idx')],
            },
        ),
    ]
