# Generated by Django 4.2.30 on 2026-07-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0022_studio_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
