# Generated by Django 4.2.30 on 2026-07-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0023_adminprofile_is_onboarding_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_created', 'New Ticket'), ('ticket_assigned', 'Ticket Assigned'), ('meeting_requested', 'Meeting Requested'), ('meeting_updated', 'Meeting Updated'), ('system_error', 'System Error'), ('ai_improvement', 'AI Needs Improvement'), ('project_submitted', 'Project Submitted'), ('project_clarify', 'Project Clarification'), ('project_approved', 'Project Approved'), ('project_completed', 'Project Completed'), ('task_submitted', 'Task Submitted'), ('task_status_changed', 'Task Status Changed'), ('assignment_responded', 'Assignment Responded'), ('message_received', 'Message Received')], max_length=20),
        ),
    ]
