# Generated by Django 5.2.8 on 2026-07-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0024_alter_systemnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='mfa_enforced_roles',
            field=models.JSONField(default=list, help_text='List of roles that require MFA, e.g. ["admin", "consultant", "pm", "client"]'),
        ),
    ]
