# Generated by Django 5.2.8 on 2026-07-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0025_systemconfig_mfa_enforced_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrole',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('operator', 'Operator/Support'), ('content_editor', 'Content Editor'), ('qa_tester', 'QA Tester')], max_length=50, unique=True),
        ),
    ]
