# Generated by Django 5.2.8 on 2026-07-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0026_alter_adminrole_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UATSignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_by_name', models.CharField(max_length=255)),
                ('signed_by_email', models.EmailField(max_length=254)),
                ('signed_by_role', models.CharField(default='ORR Stakeholder', max_length=100)),
                ('milestone_name', models.CharField(default='Final UAT & Handover', max_length=255)),
                ('agreed_to_sla', models.BooleanField(default=True)),
                ('agreed_to_defect_resolution', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('sign_off_date', models.DateTimeField(auto_now_add=True)),
                ('cryptographic_signature', models.TextField(blank=True, help_text='Optional cryptographic signature of the terms')),
            ],
        ),
    ]
