# Generated by Django 5.2.8 on 2026-07-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0028_adminprofile_created_by_adminprofile_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
