# Generated by Django 5.2.8 on 2026-08-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0030_clear_hung_locks'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='is_ai_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
