# Generated by Django 5.2.8 on 2026-08-05 09:01

import admin_portal.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0031_clientdocument_is_ai_generated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Internal name for this landing page', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('hero_title', admin_portal.fields.RichTextField(default=admin_portal.fields._default)),
                ('hero_subtitle', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('hero_image', models.URLField(blank=True, max_length=500)),
                ('section_1_title', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('section_1_content', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('section_2_title', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('section_2_content', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('section_3_title', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('section_3_content', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('cta_title', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('cta_description', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('cta_button_text', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('cta_button_link', models.CharField(blank=True, max_length=500)),
                ('meta_title', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('meta_description', admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Landing Page',
                'verbose_name_plural': 'Custom Landing Pages',
            },
        ),
        migrations.CreateModel(
            name='LetterheadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Standard ORR Letterhead'", max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('header_html', models.TextField(blank=True, help_text='HTML for the header.')),
                ('footer_html', models.TextField(blank=True, help_text='HTML for the footer.')),
                ('css_styles', models.TextField(blank=True, help_text='Custom CSS for the document.')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback_attachments/')),
                ('browser_info', models.CharField(blank=True, max_length=255)),
                ('os_info', models.CharField(blank=True, max_length=255)),
                ('url_path', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
