# Generated by Django 5.2.8 on 2026-08-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0032_customlandingpage_letterheadtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiodocument',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studiodocument',
            name='is_ai_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studiodocument',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
