# Generated by Django 5.2.8 on 2026-08-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0033_studiodocument_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrole',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('operator', 'Operator/Support'), ('qa_tester', 'QA Tester')], max_length=50, unique=True),
        ),
    ]
