# Generated by Django 5.2.8 on 2026-08-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0034_alter_adminrole_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='email_address',
            field=models.EmailField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone_number',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='email_address',
            field=models.EmailField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='phone_number',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='livingsystemspagecontent',
            name='hero_image',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='messagestrip',
            name='user_image_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='messagestrip',
            name='user_image_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='messagestrip',
            name='user_image_3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='messagestrip',
            name='user_image_4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='operationalsystemspagecontent',
            name='hero_image',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='data_intelligence_image',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='service_1_image',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='service_2_image',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='strategicadvisorypagecontent',
            name='hero_image',
            field=models.URLField(default='', max_length=500),
        ),
    ]
