# Generated by Django 4.2.30 on 2026-07-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_client_confirmation', 'Awaiting Client Confirmation'), ('awaiting_payment', 'Awaiting Payment'), ('pending_admin_review', 'Pending Admin Review'), ('needs_pm_clarification', 'Needs PM Clarification'), ('approved_for_sourcing', 'Approved for Consultant Sourcing'), ('ready_for_matching', 'Ready for Consultant Matching'), ('sourcing_internally', 'Sourcing Internally'), ('sourcing_externally', 'Sourcing Externally'), ('consultant_assignment_pending', 'Consultant Assignment Pending'), ('active', 'Active'), ('internal_review', 'Internal Review'), ('delivered', 'Delivered'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='draft', max_length=40),
        ),
    ]
