# Generated by Django 5.2.8 on 2026-08-05 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0032_customlandingpage_letterheadtemplate_and_more'),
        ('pm', '0004_pmassignment_created_by_pmassignment_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmproject',
            name='source_ticket',
            field=models.ForeignKey(blank=True, help_text='The client request/ticket this project originated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_projects', to='admin_portal.ticket'),
        ),
    ]
