# Generated by Django 4.2.30 on 2026-07-01 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACCOUNT_CREATED', 'Account Created'), ('EMAIL_VERIFIED', 'Email Verified'), ('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('NEEDS_CLARIFICATION', 'Needs Clarification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACCOUNT_CREATED', max_length=30)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('internal_rating', models.CharField(choices=[('NOT_ASSESSED', 'Not Assessed'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('PRIORITY', 'Priority')], default='NOT_ASSESSED', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_consultants', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantWorkPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('weekly_capacity', models.CharField(blank=True, max_length=50)),
                ('preferred_roles', models.JSONField(blank=True, default=list)),
                ('work_modes', models.JSONField(blank=True, default=list)),
                ('geo_coverage', models.CharField(blank=True, max_length=255)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_preference', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_specialization', models.CharField(blank=True, choices=[('Strategy Advisory & Compliance', 'Strategy Advisory & Compliance'), ('Operational Systems & Infrastructure', 'Operational Systems & Infrastructure'), ('Living Systems Regeneration', 'Living Systems Regeneration')], max_length=100)),
                ('secondary_specializations', models.JSONField(blank=True, default=list)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_name', models.CharField(max_length=200)),
                ('proficiency_level', models.CharField(blank=True, max_length=50)),
                ('years_of_experience', models.CharField(blank=True, max_length=50)),
                ('is_custom', models.BooleanField(default=False)),
                ('custom_status', models.CharField(blank=True, choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MERGED', 'Merged')], max_length=20, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('professional_title', models.CharField(blank=True, max_length=200)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantITCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('it_confidence', models.CharField(blank=True, max_length=50)),
                ('ai_familiarity', models.CharField(blank=True, max_length=50)),
                ('digital_tools', models.JSONField(blank=True, default=list)),
                ('software_experience', models.JSONField(blank=True, default=list)),
                ('data_handling', models.JSONField(blank=True, default=list)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_competence', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_summary', models.TextField(blank=True)),
                ('sector_experience', models.JSONField(blank=True, default=list)),
                ('professional_evidence', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='consultant_cvs/')),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('right_to_work', models.BooleanField(default=False)),
                ('confidentiality', models.BooleanField(default=False)),
                ('conflict_of_interest', models.BooleanField(default=False)),
                ('conflict_details', models.TextField(blank=True)),
                ('data_protection', models.BooleanField(default=False)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hourly_rate', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('engagement_types', models.JSONField(blank=True, default=list)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercials', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
