# Generated by Django 4.2.30 on 2026-07-01 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('client_sector', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('scope', models.JSONField(default=list)),
                ('deliverables', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('OFFERED', 'Offered'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OFFERED', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=20)),
                ('deliverable_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('deliverable_notes', models.TextField(blank=True)),
                ('deliverable_file_name', models.CharField(blank=True, max_length=255)),
                ('deliverable_file_url', models.URLField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='consultation.consultantjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('notif_type', models.CharField(choices=[('JOB', 'Job'), ('PAYMENT', 'Payment'), ('CHAT', 'Chat'), ('DOCUMENT', 'Document'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(choices=[('CONSULTANT', 'Consultant'), ('PROJECT_MANAGER', 'Project Manager')], max_length=20)),
                ('text', models.TextField()),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_url', models.URLField(blank=True)),
                ('attachment_type', models.CharField(blank=True, max_length=50)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=100)),
                ('join_link', models.URLField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('billing_period', models.CharField(max_length=100)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('task_title', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('PAID', 'Paid')], default='SUBMITTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('LEGAL', 'Legal'), ('FINANCIAL', 'Financial'), ('OPERATIONAL', 'Operational'), ('TECHNICAL', 'Technical')], default='LEGAL', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('doc_type', models.CharField(choices=[('doc', 'Document'), ('sheet', 'Spreadsheet'), ('slide', 'Presentation'), ('folder', 'Folder'), ('file', 'File')], default='doc', max_length=20)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked')], default='LOCKED', max_length=20)),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='consultation.consultant')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.consultantjob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
