# Generated by Django 4.2.30 on 2026-07-13 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0002_consultantjob_consultanttask_consultantnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantmessage',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
