# Generated by Django 4.2.30 on 2026-07-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultantmessage_pm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultanttask',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Under Review'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=20),
        ),
    ]
