# Generated by Django 4.2.30 on 2026-07-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_alter_consultanttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultanttask',
            name='pm_task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
