# Generated by Django 4.2.30 on 2026-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_consultanttask_pm_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantmeeting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='consultantmeeting',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='consultantmeeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultantmeeting',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
