# Generated by Django 4.2.30 on 2026-07-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_remove_consultantmeeting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
