# Generated by Django 4.2.30 on 2026-07-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_consultantprofile_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantexperience',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantexperience',
            name='current_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultantexperience',
            name='educational_qualifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantexperience',
            name='licenses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantexperience',
            name='previous_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantexperience',
            name='professional_memberships',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantexperience',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='consultantspecialization',
            name='areas_of_specialization',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantspecialization',
            name='consulting_methodologies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantspecialization',
            name='expertise_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantspecialization',
            name='industry_expertise',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
