# Generated by Django 4.2.30 on 2026-07-15 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0008_consultantexperience_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantmeeting',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
