# Generated by Django 5.2.8 on 2026-07-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_consultant_created_by_consultant_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='consultant_documents/'),
        ),
    ]
