# Generated by Django 5.2.8 on 2026-08-06 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_project_classification_project_confidentiality_level_and_more'),
        ('consultation', '0011_consultantdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantjob',
            name='consultant_feedback',
            field=models.TextField(blank=True, help_text="Consultant's initial feedback/cost upon accepting the project", null=True),
        ),
        migrations.AddField(
            model_name='consultantjob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_jobs', to='client.project'),
        ),
        migrations.AlterField(
            model_name='consultantjob',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='consultation.consultant'),
        ),
        migrations.AlterField(
            model_name='consultantjob',
            name='status',
            field=models.CharField(choices=[('REQUESTED_BY_PM', 'Requested by PM'), ('ASSIGNED_BY_ADMIN', 'Assigned by Admin'), ('ACCEPTED_BY_CONSULTANT', 'Accepted by Consultant'), ('REJECTED_BY_CONSULTANT', 'Rejected by Consultant'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED_BY_PM', max_length=30),
        ),
    ]
